//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.NHLServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchData", Namespace="http://schemas.datacontract.org/2004/07/NHLService")]
    [System.SerializableAttribute()]
    public partial class MatchData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Goal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Goal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Team1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Team2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Goal1 {
            get {
                return this.Goal1Field;
            }
            set {
                if ((this.Goal1Field.Equals(value) != true)) {
                    this.Goal1Field = value;
                    this.RaisePropertyChanged("Goal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Goal2 {
            get {
                return this.Goal2Field;
            }
            set {
                if ((this.Goal2Field.Equals(value) != true)) {
                    this.Goal2Field = value;
                    this.RaisePropertyChanged("Goal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team1 {
            get {
                return this.Team1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Team1Field, value) != true)) {
                    this.Team1Field = value;
                    this.RaisePropertyChanged("Team1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team2 {
            get {
                return this.Team2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Team2Field, value) != true)) {
                    this.Team2Field = value;
                    this.RaisePropertyChanged("Team2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlobalResults", Namespace="http://schemas.datacontract.org/2004/07/NHLService")]
    [System.SerializableAttribute()]
    public partial class GlobalResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfWinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfWins {
            get {
                return this.NumberOfWinsField;
            }
            set {
                if ((this.NumberOfWinsField.Equals(value) != true)) {
                    this.NumberOfWinsField = value;
                    this.RaisePropertyChanged("NumberOfWins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamName {
            get {
                return this.TeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamNameField, value) != true)) {
                    this.TeamNameField = value;
                    this.RaisePropertyChanged("TeamName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NHLServiceReference1.INHLStatService")]
    public interface INHLStatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INHLStatService/GetAllMatches", ReplyAction="http://tempuri.org/INHLStatService/GetAllMatchesResponse")]
        ClientApplication.NHLServiceReference1.MatchData[] GetAllMatches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INHLStatService/GetAllMatches", ReplyAction="http://tempuri.org/INHLStatService/GetAllMatchesResponse")]
        System.Threading.Tasks.Task<ClientApplication.NHLServiceReference1.MatchData[]> GetAllMatchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INHLStatService/GetAllResults", ReplyAction="http://tempuri.org/INHLStatService/GetAllResultsResponse")]
        ClientApplication.NHLServiceReference1.GlobalResults[] GetAllResults();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INHLStatService/GetAllResults", ReplyAction="http://tempuri.org/INHLStatService/GetAllResultsResponse")]
        System.Threading.Tasks.Task<ClientApplication.NHLServiceReference1.GlobalResults[]> GetAllResultsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INHLStatServiceChannel : ClientApplication.NHLServiceReference1.INHLStatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NHLStatServiceClient : System.ServiceModel.ClientBase<ClientApplication.NHLServiceReference1.INHLStatService>, ClientApplication.NHLServiceReference1.INHLStatService {
        
        public NHLStatServiceClient() {
        }
        
        public NHLStatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NHLStatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NHLStatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NHLStatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientApplication.NHLServiceReference1.MatchData[] GetAllMatches() {
            return base.Channel.GetAllMatches();
        }
        
        public System.Threading.Tasks.Task<ClientApplication.NHLServiceReference1.MatchData[]> GetAllMatchesAsync() {
            return base.Channel.GetAllMatchesAsync();
        }
        
        public ClientApplication.NHLServiceReference1.GlobalResults[] GetAllResults() {
            return base.Channel.GetAllResults();
        }
        
        public System.Threading.Tasks.Task<ClientApplication.NHLServiceReference1.GlobalResults[]> GetAllResultsAsync() {
            return base.Channel.GetAllResultsAsync();
        }
    }
}
